services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - POSTGRES_URL=postgresql://admin:123456@db-sql:5432/data_base_name
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=data_base_name
    depends_on:
      - db-sql

  db-sql:
    image: postgres:15.13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=data_base_name
    volumes:
      - database-volume:/var/lib/postgresql/data

volumes:
  database-volume:
    driver: local
    driver_opts:
      type: none
      device: ./../database-volume
      o: bind
